// Contract test between services/wardrobe_attr (the CLIP classifier) and
// lib/wardrobe_attr_client.js (the backend's parser). Catches field-name drift
// that classifier.config.test.js does not: that test mocks the response shape
// entirely, so a rename on either side would pass silently there.
const fs = require("fs");
const path = require("path");
const { normalizeAttributes, stubAttributes } = require("../lib/wardrobe_attr_client");

const SERVE_CLIP_PATH = path.join(__dirname, "../../services/wardrobe_attr/serve_clip.py");
const FIXTURE_PATH = path.join(__dirname, "../../docs/testing/evidence/services/classifier-response.json");

// Fields the client reads off the raw response (see normalizeAttributes).
const CLIENT_FIELDS = [
  "category", "subcategory", "primaryColor", "secondaryColors", "pattern",
  "fabricGuess", "formality", "warmth", "seasons", "tags",
];

test("serve_clip.py's returned dict keys match every field the backend parses", () => {
  const source = fs.readFileSync(SERVE_CLIP_PATH, "utf8");
  // Pull the quoted keys out of the literal dict the endpoint returns (see the
  // block ending in `"tags": tags,` in serve_clip.py).
  const dictBlock = source.slice(source.indexOf('"category": category'), source.indexOf('"tags": tags') + 20);
  const serviceFields = [...dictBlock.matchAll(/"(\w+)":/g)].map((m) => m[1]);

  expect(new Set(serviceFields)).toEqual(new Set(CLIENT_FIELDS));
});

test("a real captured classifier response survives normalization unchanged", () => {
  // docs/testing/evidence/services/classifier-response.json is captured by
  // services/smoke_http.py against the actual running service, not a mock —
  // if the service renames or drops a field, this fixture (regenerated by the
  // smoke test) stops matching what the client expects and this test fails.
  const raw = JSON.parse(fs.readFileSync(FIXTURE_PATH, "utf8"));
  expect(new Set(Object.keys(raw))).toEqual(new Set(CLIENT_FIELDS));

  const normalized = normalizeAttributes(raw, stubAttributes());
  // Every field from the real response must have been carried through, not
  // silently replaced by the stub default because of a name mismatch.
  expect(normalized).toEqual({
    ...raw,
    formality: Math.min(5, Math.max(1, Math.round(raw.formality))),
    warmth: Math.min(5, Math.max(1, Math.round(raw.warmth))),
  });
});
